rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba-nt/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba-nt/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba-nt/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba-nt/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba-nt-tagged/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba-nt-tagged/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba-nt-tagged/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-ewe-igbo-yoruba-nt-tagged/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-haitian-creole/model_200000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-haitian-creole/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-haitian-creole/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-haitian-creole/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-haitian-creole/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-hiligaynon/model_200000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-hiligaynon/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-hiligaynon/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-hiligaynon/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-hiligaynon/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-hiligaynon-maori-nt-vietnamese/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-hiligaynon-maori-nt-vietnamese/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-hiligaynon-maori-nt-vietnamese/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-hiligaynon-maori-nt-vietnamese/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-igbo/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-igbo/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-igbo/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-igbo/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-maori/model_200000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-maori/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-maori/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-maori/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-maori/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-yoruba/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-yoruba/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-yoruba/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-yoruba/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-yoruba-nt/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-yoruba-nt/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-yoruba-nt/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_custom_open-bible-yoruba-nt/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_pinyin_open-bible-vietnamese/model_200000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_pinyin_open-bible-vietnamese/model_210000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_pinyin_open-bible-vietnamese/model_220000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_pinyin_open-bible-vietnamese/model_230000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/F5TTS_v1_Base_vocos_pinyin_open-bible-vietnamese/model_240000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-maori-nt-finetune/model_10000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-maori-nt-finetune/model_20000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-maori-nt-finetune/model_30000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-maori-nt-finetune/model_40000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-maori-nt-finetune/model_50000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-maori-nt-finetune/model_60000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-maori-nt-finetune/model_70000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-maori-nt-finetune/model_80000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-maori-nt-finetune/model_90000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-yoruba-nt-finetune/model_10000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-yoruba-nt-finetune/model_20000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-yoruba-nt-finetune/model_30000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-yoruba-nt-finetune/model_40000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-yoruba-nt-finetune/model_50000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-yoruba-nt-finetune/model_60000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-yoruba-nt-finetune/model_70000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-yoruba-nt-finetune/model_80000.pt
rm -rf /home/mila/g/guzmand/scratch/Repositories/open-bible-models/F5-TTS/ckpts/open-bible-yoruba-nt-finetune/model_90000.pt